const maisVendidos = [
    {
        id: "cafe-com-deus-pai-2025",
        titulo: "Café com Deus Pai 2025: Porções Diárias de Transformação",
        autor: "Júnior Rostirola",
        posicao: "#1",
        imagem: "https://m.media-amazon.com/images/I/5109YEIX0kL._SY425_.jpg",
        link: "https://amzn.to/4iUfJx7",
    },
    {
        id: "o-homem-mais-rico-da-babilonia",
        titulo: "O homem mais rico da Babilônia",
        autor: "George S Clason",
        posicao: "#2",
        imagem: "https://m.media-amazon.com/images/I/81ehX6Quw2L._SY425_.jpg",
        link: "https://amzn.to/40bLPxl",
    },
    {
        id: "a-psicologia-financeira",
        titulo: "A psicologia financeira",
        autor: "Morgan Housel",
        posicao: "#3",
        imagem: "https://m.media-amazon.com/images/I/81ehvI03NYS._SY425_.jpg",
        link: "https://amzn.to/3PyqckJ",
    },
    {
        id: "verity",
        titulo: "Verity",
        autor: "Colleen Hoover",
        posicao: "#4",
        imagem: "https://m.media-amazon.com/images/I/91SDZ2eUj+L._SY425_.jpg",
        link: "https://amzn.to/4fvEYmN",
    },
    {
        id: "forte",
        titulo: "Forte: Devocionais para uma vida poderosa e apaixonada",
        autor: "Lisa Bevere",
        posicao: "#5",
        imagem: "https://m.media-amazon.com/images/I/81iP98T6pwL._SY342_.jpg",
        link: "https://amzn.to/4fvF91m",
    },
    {
        id: "habitos-atomicos",
        titulo: "Hábitos Atômicos: um Método Fácil e Comprovado de Criar Bons Hábitos e se Livrar dos Maus",
        autor: "James Clear",
        posicao: "#6",
        imagem: "https://m.media-amazon.com/images/I/81eT2pjx4jL._SY425_.jpg",
        link: "https://amzn.to/3PdTMvn",
    },
    {
        id: "cem-anos-de-solidao",
        titulo: "Cem anos de solidão",
        autor: "Gabriel Garcia Marquez",
        posicao: "#7",
        imagem: "https://m.media-amazon.com/images/I/817esPahlrL._SY466_.jpg",
        link: "https://amzn.to/4iW2SdR",
    },
    {
        id: "como-falar-sobre-sexualidade-com-as-criancas",
        titulo: "Como falar sobre sexualidade com as crianças: Um guia prático de educação sexual infantil para pais",
        autor: "Leiliane Rocha",
        posicao: "#8",
        imagem: "https://m.media-amazon.com/images/I/61fsQjG2Q1L._SY466_.jpg",
        link: "https://amzn.to/3PjXJi5",
    },
    {
        id: "a-hora-da-estrela",
        titulo: "A hora da estrela",
        autor: "Clarice Lispector",
        posicao: "#9",
        imagem: "https://m.media-amazon.com/images/I/61TaHURu27L._SL1000_.jpg",
        link: "https://amzn.to/40bPcnY",
    },
    {
        id: "a-morte",
        titulo: "A morte é um dia que vale a pena viver: E um excelente motivo para se buscar um novo olhar para a vida",
        autor: "Ana Claudia Quintana Arantes",
        posicao: "#10",
        imagem: "https://m.media-amazon.com/images/I/615KDfCxHFL._SY466_.jpg",
        link: "https://amzn.to/3VRJAwA",
    },
    {
        id: "como-fazer-amigos-e-influenciar-pessoas",
        titulo: "Como fazer amigos e influenciar pessoas",
        autor: "Dale Carnegie",
        posicao: "#11",
        imagem: "https://m.media-amazon.com/images/I/71x-i7sKSvL._SY425_.jpg",
        link: "https://amzn.to/4gx9y0n",
    },
    {
        id: "como-se-tornar-sobrenatural",
        titulo: "Como se tornar sobrenatural: Pessoas comuns realizando o extraordinário",
        autor: "Dr. Joe Dizpenza",
        posicao: "#12",
        imagem: "https://m.media-amazon.com/images/I/61miHJ2Wx2L._SY466_.jpg",
        link: "https://amzn.to/4gUhMiT",
    },
]

export default maisVendidos
    