import autores from "./autores";

const series = [
  {
    id: "harry-potter",
    titulo: "Harry Potter",
    descricao:
      "A série de livros Harry Potter, escrita por J.K. Rowling, segue a jornada de um jovem bruxo, Harry Potter, enquanto ele descobre seu lugar no mundo mágico e enfrenta desafios para derrotar o malvado bruxo Lord Voldemort. Ao longo de sete livros, Harry e seus amigos, Hermione Granger e Ron Weasley, exploram a magia, enfrentam perigos e aprendem sobre amizade, coragem e o poder da escolha em uma luta épica entre o bem e o mal.",
    autor: autores[0],
    ano: 1997,
    imagem:
      "https://ingresso-a.akamaihd.net/b2b/production/uploads/article/image/2549/7ababc2015043445b750ebc853a5f706.jpg",
    livros: [
      {
        id: "harry-potter-e-a-pedra-filosofal",
        titulo: "Harry Potter e a Pedra Filosofal",
        autor: autores[0],
        ano: 1997,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81pB+joKL4L._SL1500_.jpg",
        link: "https://amzn.to/49heZ0X",
      },
      {
        id: "harry-potter-e-a-camara-secreta",
        titulo: "Harry Potter e a Câmara Secreta",
        autor: autores[0],
        ano: 1998,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/81D+5aMHzFL._SL1500_.jpg",
        link: "https://amzn.to/3B702Sg",
      },
      {
        id: "harry-potter-e-o-prisioneiro-de-azkaban",
        titulo: "Harry Potter e o Prisioneiro de Azkaban",
        autor: autores[0],
        ano: 1999,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81Q+2zleuwL._SL1500_.jpg",
        link: "https://amzn.to/3B46wS0",
      },
      {
        id: "harry-potter-e-o-calice-de-fogo",
        titulo: "Harry Potter e o Cálice de Fogo",
        autor: autores[0],
        ano: 2000,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/81IsnaNraBL._SL1500_.jpg",
        link: "https://amzn.to/41d45ay",
      },
      {
        id: "harry-potter-e-a-ordem-da-fenix",
        titulo: "Harry Potter e a Ordem da Fênix",
        autor: autores[0],
        ano: 2003,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/81ZQUV67MGL._SL1500_.jpg",
        link: "https://amzn.to/3Zw4ZgU",
      },
      {
        id: "harry-potter-e-o-enigma-do-principe",
        titulo: "Harry Potter e o Enigma do Príncipe",
        autor: autores[0],
        ano: 2005,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/81SZC96OGOL._SL1500_.jpg",
        link: "https://amzn.to/4ibXDXg",
      },
      {
        id: "Harry Potter e as Reliquias da Morte",
        titulo: "Harry Potter e as Relíquias da Morte",
        autor: autores[0],
        ano: 2007,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/81PbdwXqKkL._SL1500_.jpg",
        link: "https://amzn.to/3CUdBFl",
      },
      {
        id: "harry-potter-e-a-crianca-amaldicoada",
        titulo: "Harry Potter e a Criança Amaldiçoada",
        autor: autores[0],
        ano: 2016,
        ordem: 8,
        imagem: "https://rocco.com.br/app/uploads/2024/04/9786555322682.jpg",
        link: "https://amzn.to/3ZevtlR",
      },
    ],
  },
  {
    id: "o-senhor-dos-aneis",
    titulo: "O Senhor dos Anéis",
    descricao:
      "A trilogia O Senhor dos Anéis, escrita por J.R.R. Tolkien, narra a aventura épica de Frodo Bolseiro, um hobbit que recebe a missão de destruir o poderoso Anel do Poder e impedir que ele caia nas mãos do sombrio Senhor Sauron. Acompanhado por um grupo diverso de heróis, Frodo enfrenta batalhas, perigos sobrenaturais e tentações, em uma jornada que explora temas de coragem, sacrifício e amizade. A história celebra a luta do bem contra o mal em um vasto e detalhado mundo de fantasia, a Terra-média.",
    autor: autores[1],
    ano: 1954,
    imagem:
      "https://cinepop.com.br/wp-content/uploads/2021/12/o-senhor-dos-aneis.jpg",
    livros: [
      {
        id: "a-sociedade-do-anel",
        titulo: "A Sociedade do Anel",
        autor: autores[1],
        ano: 1954,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg",
        link: "https://amzn.to/49htqlr",
      },
      {
        id: "as-duas-torres",
        titulo: "As Duas Torres",
        autor: autores[1],
        ano: 1954,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/81N9hxO6XdL._SL1500_.jpg",
        link: "https://amzn.to/3CMSgxm",
      },
      {
        id: "o-retorno-do-rei",
        titulo: "O Retorno do Rei",
        autor: autores[1],
        ano: 1955,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81LUEEYfQNL._SL1500_.jpg",
        link: "https://amzn.to/3D1Tmp0",
      },
    ],
  },
  {
    id: "as-cronicas-de-gelo-e-fogo",
    titulo: "As Crônicas de Gelo e Fogo",
    descricao:
      "As Crônicas de Gelo e Fogo, série escrita por George R.R. Martin, acompanha a luta pelo Trono de Ferro em Westeros, um continente marcado por rivalidades, alianças e traições. Nobres famílias, como os Starks, Lannisters e Targaryens, jogam um perigoso jogo de intrigas, onde poder e sobrevivência andam lado a lado. Enquanto reis e rainhas disputam o controle dos Sete Reinos, uma antiga ameaça cresce ao norte, e o inverno se aproxima, trazendo consigo o perigo dos Caminhantes Brancos. A série explora temas de poder, lealdade e moralidade em uma narrativa complexa e repleta de reviravoltas.",
    autor: autores[2],
    ano: 1996,
    imagem:
      "https://img.odcdn.com.br/wp-content/uploads/2024/07/Design-sem-nome-16-1-scaled.jpg",
    livros: [
      {
        id: "a-guerra-dos-tronos",
        titulo: "A Guerra dos Tronos",
        autor: autores[2],
        ano: 1996,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/91eHityofNL._SL1500_.jpg",
        link: "https://amzn.to/3CWfCAY",
      },
      {
        id: "a-furia-dos-reis",
        titulo: "A Fúria dos Reis",
        autor: autores[2],
        ano: 1998,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91N6C0jwzuL._SL1500_.jpg",
        link: "https://amzn.to/3ZckitU",
      },
      {
        id: "a-tormenta-de-espadas",
        titulo: "A Tormenta de Espadas",
        autor: autores[2],
        ano: 2000,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/91VVZ-v5GYL._SL1500_.jpg",
        link: "https://amzn.to/3CSvhBc",
      },
      {
        id: "o-festim-dos-corvos",
        titulo: "O Festim dos Corvos",
        autor: autores[2],
        ano: 2019,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/814UZhEYFfL._SL1500_.jpg",
        link: "https://amzn.to/3ZtIRUu",
      },
      {
        id: "a-danca-dos-dragoes",
        titulo: "A Dança dos Dragões",
        autor: autores[2],
        ano: 2020,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/91DisjRjFxL._SL1500_.jpg",
        link: "https://amzn.to/3Ozr8os",
      },
    ],
  },
  {
    id: "diario-de-um-banana",
    titulo: "Diário de um Banana",
    descricao:
      "Diário de um Banana é uma série de livros infantojuvenis escrita por Jeff Kinney, que combina humor, ilustrações em estilo de tirinhas e histórias cativantes sobre a vida de Greg Heffley, um adolescente comum que enfrenta os altos e baixos da escola e da convivência com sua peculiar família. Com um tom leve e bem-humorado, a série aborda temas como amizade, desafios escolares, embaraços do crescimento e as aventuras do cotidiano de forma acessível e divertida. Os livros têm um estilo de narrativa em forma de diário ilustrado, que conquistou milhões de leitores ao redor do mundo, tornando-se um fenômeno da literatura juvenil.",
    autor: autores[3],
    ano: 2007,
    imagem:
      "https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2021/11/13/1443507557-diary-of-a-wimpy-kid.jpg",
    livros: [
      {
        id: "diario-de-um-banana-1",
        titulo: "Diário de um Banana 1",
        autor: autores[3],
        ano: 2008,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/71fWaI5myqL._SY385_.jpg",
        link: "https://amzn.to/4f0OOwy",
      },
      {
        id: "diario-de-um-banana-2",
        titulo: "Diário de um Banana 2: Rodrick é o cara",
        autor: autores[3],
        ano: 2009,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/71+fh2vstSL._SY385_.jpg",
        link: "https://amzn.to/4197nv9",
      },
      {
        id: "diario-de-um-banana-3",
        titulo: "Diário de um Banana 3: A gota d’água",
        autor: autores[3],
        ano: 2010,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81T9BY8yEnL._SY385_.jpg",
        link: "https://amzn.to/41aONCS",
      },
      {
        id: "diario-de-um-banana-4",
        titulo: "Diário de um Banana 4: Dias de Cão",
        autor: autores[2],
        ano: 2011,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/71MuD6Hn8OL._SY385_.jpg",
        link: "https://amzn.to/4g8O1us",
      },
      {
        id: "diario-de-um-banana-5",
        titulo: "Diário de um Banana 5: A verdade nua e crua",
        autor: autores[3],
        ano: 2011,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/711dw9VO+jL._SY385_.jpg",
        link: "https://amzn.to/4g8zcYT",
      },
      {
        id: "diario-de-um-banana-6",
        titulo: "Diário de um Banana 6: Casa dos horrores",
        autor: autores[3],
        ano: 2012,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/71beaUwsF0L._SY385_.jpg",
        link: "https://amzn.to/4g9VrO8",
      },
      {
        id: "diario-de-um-banana-7",
        titulo: "Diário de um Banana 7: Segurando vela",
        autor: autores[3],
        ano: 2013,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/71gWCy-KesL._SY385_.jpg",
        link: "https://amzn.to/3VhvmEC",
      },
      {
        id: "diario-de-um-banana-8",
        titulo: "Diário de um Banana 8: Maré de azar",
        autor: autores[3],
        ano: 2014,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/716yGyLTIxL._SY385_.jpg",
        link: "https://amzn.to/3VhvpQO",
      },
      {
        id: "diario-de-um-banana-9",
        titulo: "Diário de um Banana 9: Caindo na estrada",
        autor: autores[3],
        ano: 2015,
        ordem: 9,
        imagem: "https://m.media-amazon.com/images/I/71D7-E0gtIL._SY385_.jpg",
        link: "https://amzn.to/4f3qOJq",
      },
      {
        id: "diario-de-um-banana-10",
        titulo: "Diário de um Banana 10: Bons tempos",
        autor: autores[3],
        ano: 2015,
        ordem: 10,
        imagem: "https://m.media-amazon.com/images/I/71ci78zaT-L._SY385_.jpg",
        link: "https://amzn.to/4fRin4O",
      },
      {
        id: "diario-de-um-banana-11",
        titulo: "Diário de um Banana 11: Vai ou racha",
        autor: autores[3],
        ano: 2016,
        ordem: 11,
        imagem: "https://m.media-amazon.com/images/I/718cIIlLIwL._SY385_.jpg",
        link: "https://amzn.to/3B8g12E",
      },
      {
        id: "diario-de-um-banana-12",
        titulo: "Diário de um Banana 12: Apertem os cintos",
        autor: autores[3],
        ano: 2017,
        ordem: 12,
        imagem: "https://m.media-amazon.com/images/I/71vHGC4hRmL._SY385_.jpg",
        link: "https://amzn.to/3B2fwXP",
      },
      {
        id: "diario-de-um-banana-13",
        titulo: "Diário de um Banana 13: Batalha Neval",
        autor: autores[3],
        ano: 2018,
        ordem: 13,
        imagem: "https://m.media-amazon.com/images/I/71AII-WDnXL._SY385_.jpg",
        link: "https://amzn.to/4idwbIA",
      },
      {
        id: "diario-de-um-banana-14",
        titulo: "Diário de um Banana 14: Quebra Tudo",
        autor: autores[3],
        ano: 2019,
        ordem: 14,
        imagem: "https://m.media-amazon.com/images/I/71RqnIKaA9L._SY385_.jpg",
        link: "https://amzn.to/3CTuOi3",
      },
      {
        id: "diario-de-um-banana-15",
        titulo: "Diário de um Banana 15: Vai Fundo",
        autor: autores[3],
        ano: 2020,
        ordem: 15,
        imagem: "https://m.media-amazon.com/images/I/71qp05Xbw9L._SY385_.jpg",
        link: "https://amzn.to/4fSEYy1",
      },
      {
        id: "diario-de-um-banana-16",
        titulo: "Diário de um Banana 16: Bola Fora",
        autor: autores[3],
        ano: 2021,
        ordem: 16,
        imagem: "https://m.media-amazon.com/images/I/91Bd39WTNuL._SY385_.jpg",
        link: "https://amzn.to/3VfwIQm",
      },
      {
        id: "diario-de-um-banana-17",
        titulo: "Diário de um Banana 17: Fräwda Megaxeia",
        autor: autores[3],
        ano: 2022,
        ordem: 17,
        imagem: "https://m.media-amazon.com/images/I/916K1XCNRBL._UF894,1000_QL80_.jpg",
        link: "https://amzn.to/3VkQdqL",
      },
      {
        id: "diario-de-um-banana-18",
        titulo: "Diário de um Banana 18: Cabeça-oca",
        autor: autores[3],
        ano: 2023,
        ordem: 18,
        imagem: "https://m.media-amazon.com/images/I/71HODD5GbdL._AC_UF1000,1000_QL80_.jpg",
        link: "https://amzn.to/4eVdIOd",
      },
      {
        id: "diario-de-um-banana-19",
        titulo: "Diário de um Banana 19: Baita lambança",
        autor: autores[3],
        ano: 2024,
        ordem: 19,
        imagem: "https://m.media-amazon.com/images/I/71GJo0STB8L._SY385_.jpg",
        link: "https://amzn.to/3D2gC6h",
      },
    ],
  },
  {
    id: "maze-runner",
    titulo: "Maze Runner",
    descricao:
      "Maze Runner, de James Dashner, é uma série de ficção científica que acompanha Thomas, um jovem que acorda sem memória em uma Clareira cercada por um misterioso labirinto cheio de perigos. Junto com outros adolescentes, ele precisa desvendar os segredos por trás do labirinto e enfrentar desafios mortais em um mundo pós-apocalíptico. Com uma narrativa repleta de ação, suspense e reviravoltas, a série explora temas de sobrevivência, amizade e sacrifício, conquistando leitores ao redor do mundo.",
    autor: autores[4],
    ano: 1992,
    imagem:
      "https://i0.wp.com/tapipocando.com.br/wp-content/uploads/2024/05/Maze-Runner.jpg?fit=1920%2C1080&ssl=1",
    livros: [
      {
        id: "maze-runner-1",
        titulo: "Maze Runner: ordem de extermínio",
        autor: autores[4],
        ano: 2013,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/61ILpNSiAuL._SY385_.jpg",
        link: "https://amzn.to/49huiqd",
      },
      {
        id: "maze-runner-2",
        titulo: "Maze Runner: Arquivos",
        autor: autores[4],
        ano: 2014,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/51MTj2LpsQL._SY385_.jpg",
        link: "https://amzn.to/4eTDylE",
      },
      {
        id: "maze-runner-3",
        titulo: "Maze Runner: Correr ou Morrer",
        autor: autores[4],
        ano: 2010,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/51UqHWh58-L._SY445_SX342_.jpg",
        link: "https://amzn.to/49dil4M",
      },
      {
        id: "maze-runner-4",
        titulo: "Maze Runner: Prova de Fogo",
        autor: autores[4],
        ano: 2011,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/61pGP-2ZaCL._SY385_.jpg",
        link: "https://amzn.to/3COnapk",
      },
      {
        id: "maze-runner-5",
        titulo: "Maze Runner: A Cura Mortal",
        autor: autores[4],
        ano: 2012,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/61pR3wqzNgL._SY385_.jpg",
        link: "https://amzn.to/49fq822",
      },
      {
        id: "maze-runner-6",
        titulo: "Crank Palace: A Maze Runner Novella",
        autor: autores[4],
        ano: 2012,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/81AtmD2CM2L._SY385_.jpg",
        link: "https://amzn.to/4g9QBAq",
      },
      {
        id: "maze-runner-7",
        titulo: "Box Maze Runner - Edição completa",
        autor: autores[4],
        ano: 2018,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/81UckzVmQPL._SY385_.jpg",
        link: "https://amzn.to/3B80pMm",
      },
      
    ],
  },
  {
    id: "duna",
    titulo: "Duna",
    descricao:
      "Duna, de Frank Herbert, é uma saga épica de ficção científica que se passa em um futuro distante, em um universo dominado por intrigas políticas, conflitos religiosos e disputas por poder. A história central segue Paul Atreides, herdeiro de uma nobre casa, enquanto ele enfrenta desafios em Arrakis, um planeta desértico vital para o império por ser a única fonte da especiaria melange, a substância mais valiosa do universo. Repleto de personagens complexos e temas profundos como ecologia, messianismo e o impacto do poder, Duna é considerado um marco da literatura, inspirando gerações de leitores e cineastas.",
    autor: autores[4],
    ano: 1965,
    imagem:
      "https://sm.ign.com/ign_br/movie/d/dune/dune_1947.jpg",
    livros: [
      {
        id: "duna-1",
        titulo: "Duna",
        autor: autores[5],
        ano: 1965,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81zN7udGRUL._SY385_.jpg",
        link: "https://amzn.to/3VlZkYq",
      },
      {
        id: "duna-2",
        titulo: "Messias de Duna",
        autor: autores[5],
        ano: 1969,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91iLyWRwmRL._SY385_.jpg",
        link: "https://amzn.to/4fSDGmN",
      },
      {
        id: "duna-3",
        titulo: "Filhos de Duna",
        autor: autores[5],
        ano: 1976,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/810pYklnGsL._SY385_.jpg",
        link: "https://amzn.to/4iheojJ",
      },
      {
        id: "duna-4",
        titulo: "Imperador-Deus de Duna",
        autor: autores[5],
        ano: 1981,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/91XCwEX5fiL._SY385_.jpg",
        link: "https://amzn.to/4eW2Yzc",
      },
      {
        id: "duna-5",
        titulo: "Hereges de Duna",
        autor: autores[5],
        ano: 1984,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/61HtrwULeBL._SY385_.jpg",
        link: "https://amzn.to/4ifQ7KL",
      },
      {
        id: "duna-6",
        titulo: "Herdeiras de Duna",
        autor: autores[5],
        ano: 1984,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/61zKJw+JQRL._SY385_.jpg",
        link: "https://amzn.to/49gQHnv",
      },      
    ],
  },
  {
    id: "outlander",
    titulo: "Outlander",
    descricao:
      "Outlander, de Diana Gabaldon, é uma série de romances que mistura história, romance e fantasia. A trama acompanha Claire Randall, uma enfermeira da Segunda Guerra Mundial que, ao visitar um círculo de pedras na Escócia, é misteriosamente transportada para o século XVIII. Lá, ela se vê envolvida em uma teia de intrigas políticas e amorosas, especialmente ao conhecer Jamie Fraser, um carismático guerreiro escocês. Combinando cenários históricos ricos, personagens cativantes e um enredo emocionante, Outlander explora temas como amor, lealdade, sobrevivência e o impacto do tempo.",
    autor: autores[6],
    ano: 1991,
    imagem:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjjpo0HWjlKIfCCjRubIqCMf95ipVbfg_zP8JLYSveSf4Ya03s_TdGPhT21AmlrIyfznkZ5IQiDo8Nz5PSlkxRCb7QzqS20mxdPmS-RycX1LEH297NR7CBBt3P1HlJ51KLCK1ipNjIC8IM/w1200-h630-p-k-no-nu/outlander-livro-1-volume-1-diana-gabaldon-a-viajante-do-tempo-claire-james-starz-serie-tv-resenha-blog-leitora-viciada-capa.png",
    livros: [
      {
        id: "outlander-1",
        titulo: "A Viajante do Tempo",
        autor: autores[6],
        ano: 1991,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/61C4rFG-oYL._SY385_.jpg",
        link: "https://amzn.to/4fdB8P7",
      },
      {
        id: "outlander-2",
        titulo: "A Libélula no Âmbar",
        autor: autores[6],
        ano: 1992,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/71N1LwdVFEL._SY385_.jpg",
        link: "https://amzn.to/3OwQ3ca",
      },
      {
        id: "outlander-3",
        titulo: "O Resgate no Mar",
        autor: autores[6],
        ano: 1994,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/61tpKt86eXL._SY385_.jpg",
        link: "https://amzn.to/4iheojJ",
      },
      {
        id: "outlander-4",
        titulo: "Os Tambores de Outono",
        autor: autores[6],
        ano: 1996,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/61sf584vtmL._SY385_.jpg",
        link: "https://amzn.to/3Vk8kx5",
      },
      {
        id: "outlander-5",
        titulo: "A Cruz de Fogo",
        autor: autores[6],
        ano: 2001,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/81fcFqkUbGL._SY385_.jpg",
        link: "https://amzn.to/49p9bCr",
      },
      {
        id: "outlander-6",
        titulo: "Um Sopro de Neve e Cinzas",
        autor: autores[6],
        ano: 2005,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/91m536AwQwL._SY385_.jpg",
        link: "https://amzn.to/4eYVc7J",
      },      
      {
        id: "outlander-7",
        titulo: "Ecos do Futuro",
        autor: autores[6],
        ano: 2009,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/81Y4YAmBR4L._SY385_.jpg",
        link: "https://amzn.to/4fKnmV3",
      },      
      {
        id: "outlander-8",
        titulo: "Escrito com o Sangue do Meu Coração",
        autor: autores[6],
        ano: 2014,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/919S+MeMzkL._SY385_.jpg",
        link: "https://amzn.to/4i8iSJo",
      },      
      {
        id: "outlander-9",
        titulo: "Diga às Abelhas que não Estou mais Aqui",
        autor: autores[6],
        ano: 2021,
        ordem: 9,
        imagem: "https://m.media-amazon.com/images/I/81yPcolgsuL._SY385_.jpg",
        link: "https://amzn.to/3BcAYJF",
      },      
    ],
  },
  {
    id: "os-detetives-do-predio-azul",
    titulo: "Os Detetives do Prédio Azul",
    descricao:
      "Detetives do Prédio Azul (D.P.A.) é uma série infantojuvenil criada por Flávia Lins e Silva, que mistura mistério, aventura e diversão. A história acompanha um trio de amigos — Pippo, Sol e Bento — que vive em um prédio onde coisas estranhas e mágicas acontecem. Com capas coloridas e muita criatividade, eles formam o clube secreto dos Detetives do Prédio Azul, investigando casos misteriosos, lidando com vizinhos excêntricos e enfrentando bruxarias inesperadas. A série combina humor, enigmas e amizade, cativando crianças e despertando a curiosidade com suas histórias envolventes e cheias de imaginação.",
    autor: autores[7],
    ano: 2013,
    imagem:
      "https://muralzinhodeideias.com.br/wp-content/uploads/2023/11/dpa-apeca-Douglas-Jaco.png",
    livros: [
      {
        id: "os-detetives-do-predio-azul-1",
        titulo: "Os detetives do Prédio Azul: Primeiros casos",
        autor: autores[7],
        ano: 2013,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/91AkpDJouPL._SY385_.jpg",
        link: "https://amzn.to/3BdOf4C",
      },
      {
        id: "os-detetives-do-predio-azul-2",
        titulo: "Os detetives do Prédio Azul: Os mistérios de Mila",
        autor: autores[7],
        ano: 2014,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91TeXWU9RzL._SY385_.jpg",
        link: "https://amzn.to/4giSUkJ",
      },
      {
        id: "os-detetives-do-predio-azul-3",
        titulo: "Os detetives do Prédio Azul: Aventuras culinárias",
        autor: autores[7],
        ano: 2016,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/91oygY30N9L._SY385_.jpg",
        link: "https://amzn.to/3CZ4N0Z",
      },
      {
        id: "os-detetives-do-predio-azul-4",
        titulo: "Os detetives do prédio azul: Casos ecológicos: 4",
        autor: autores[7],
        ano: 2022,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/81z1InV7onL._SY385_.jpg",
        link: "https://amzn.to/4f6YyoV",
      },
      
    ],
  },
  {
    id: "diario-de-pilar",
    titulo: "Diário de Pilar",
    descricao:
      "Diário de Pilar, de Flávia Lins e Silva, é uma série de livros infantojuvenis que mistura aventura, cultura e fantasia. A protagonista, Pilar, é uma menina curiosa e cheia de imaginação que, junto com seu inseparável amigo Breno e o gato Samba, viaja para lugares incríveis usando uma rede mágica. Cada aventura a leva a um destino diferente, como Grécia, Egito e Japão, onde ela descobre mitos, tradições e histórias fascinantes. Com uma narrativa leve e educativa, Diário de Pilar encanta leitores ao unir diversão com aprendizado sobre o mundo e suas culturas.",
    autor: autores[7],
    ano: 2010,
    imagem:
      "https://www.monoanimation.com.br/wp-content/uploads/2019/04/teste03.-Pilar_grecia_Abertura-e-EP-01_V%C3%B4o-Livre.jpg",
    livros: [
      {
        id: "diario-de-pilar-1",
        titulo: "Diário de Pilar na Grécia",
        autor: autores[7],
        ano: 2010,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/91K6PTWRdLL._SY385_.jpg",
        link: "https://amzn.to/49jNh3s",
      },
      {
        id: "diario-de-pilar-2",
        titulo: "Diário de Pilar na Amazônia",
        autor: autores[7],
        ano: 2012,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91U9l2oN-NL._SY385_.jpg",
        link: "https://amzn.to/3VmUgTy",
      },
      {
        id: "diario-de-pilar-3",
        titulo: "Diário de Pilar no Egito",
        autor: autores[7],
        ano: 2013,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/914ObIJxC-L._SY385_.jpg",
        link: "https://amzn.to/4fU8OST",
      },
      {
        id: "diario-de-pilar-4",
        titulo: "Diário de Pilar na China",
        autor: autores[7],
        ano: 2015,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/91VTYTkBwcL._SY385_.jpg",
        link: "https://amzn.to/4eYN1YR",
      },
      {
        id: "diario-de-pilar-5",
        titulo: "Diário de Pilar na Índia",
        autor: autores[7],
        ano: 2018,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/A1T3-AY8TUL._SY385_.jpg",
        link: "https://amzn.to/4ggg23m",
      },
      {
        id: "diario-de-pilar-6",
        titulo: "Diário de Pilar na África",
        autor: autores[7],
        ano: 2020,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/51s3CdCanML._SY445_SX342_.jpg",
        link: "https://amzn.to/4eWE8iA",
      },
      {
        id: "diario-de-pilar-7",
        titulo: "Diário de Pilar em Machu Picchu",
        autor: autores[7],
        ano: 2022,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/71JbaxJPBQL._SY385_.jpg",
        link: "https://amzn.to/3BceVmp",
      },
      {
        id: "diario-de-pilar-8",
        titulo: "Diário de Pilar na Amazônia: Urgente",
        autor: autores[7],
        ano: 2023,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/91gvg5ZsstL._SY385_.jpg",
        link: "https://amzn.to/41hIBJy",
      },
      
    ],
  },
  {
    id: "socorro-cai-dentro-do-videogame",
    titulo: "Socorro! Caí Dentro do Videogame",
    descricao:
      "Socorro! Caí Dentro do Videogame, de Dustin Brady, é uma série de livros de aventura e humor que leva os leitores para dentro de emocionantes mundos digitais. A história segue Jesse e Eric, dois amigos que acabam presos em um videogame de última geração. Para escapar, eles precisam superar níveis repletos de desafios, perigos e bugs inesperados. Com ação frenética, humor inteligente e muitas referências ao universo dos games, a série encanta jovens leitores, explorando amizade, criatividade e o espírito de superação em meio a aventuras eletrizantes.",
    autor: autores[8],
    ano: 2021,
    imagem:
      "https://i0.wp.com/geekpopnews.com.br/wp-content/uploads/2021/09/Socorro-cai-dentro-do-videogame-CAPA.jpg?fit=1200%2C675&ssl=1",
    livros: [
      {
        id: "socorro-cai-dentro-do-videogame-1",
        titulo: "Socorro, caí dentro do videogame",
        autor: autores[8],
        ano: 2021,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/813qC-wJ-VL._SY385_.jpg",
        link: "https://amzn.to/3OFjJnj",
      },
      {
        id: "socorro-cai-dentro-do-videogame-2",
        titulo: "Socorro, caí dentro do videogame - Missão invisível",
        autor: autores[8],
        ano: 2022,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/61r-9MkRsWL._SY385_.jpg",
        link: "https://amzn.to/4fYdRl5",
      },
      {
        id: "socorro-cai-dentro-do-videogame-3",
        titulo: "Socorro, caí dentro do videogame - A revolta dos robôs",
        autor: autores[8],
        ano: 2022,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81vNWgSVo5L._SY385_.jpg",
        link: "https://amzn.to/4gjnxGJ",
      },
      {
        id: "socorro-cai-dentro-do-videogame-4",
        titulo: "Socorro, caí dentro do videogame - Retorno à ilha perdida",
        autor: autores[8],
        ano: 2022,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/71hqZuZY4-L._SY385_.jpg",
        link: "https://amzn.to/4g9HD6i",
      },
      {
        id: "socorro-cai-dentro-do-videogame-5",
        titulo: "Socorro, caí dentro do videogame - O último chefão",
        autor: autores[8],
        ano: 2022,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/61oqYemIbSL._SY385_.jpg",
        link: "https://amzn.to/3OCQuS2",
      },
      {
        id: "socorro-cai-dentro-do-videogame-6",
        titulo: "Box – Socorro, caí dentro do videogame",
        autor: autores[8],
        ano: 2023,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/71ieul6Qy3L._SX606_.jpg",
        link: "https://amzn.to/3Ziyp0Q",
      },     
      
    ],
  },
  {
    id: "as-aventuras-do-capitao-cueca",
    titulo: "As aventuras do Capitão Cueca",
    descricao:
      "As Aventuras do Capitão Cueca, de Dav Pilkey, é uma série de livros infantojuvenis que combina humor, criatividade e muitas trapalhadas. A história acompanha Jorge e Haroldo, dois amigos inseparáveis que adoram criar histórias em quadrinhos e pregar peças. Quando hipnotizam acidentalmente o mal-humorado diretor da escola, ele se transforma no hilário e atrapalhado Capitão Cueca, um super-herói improvável que enfrenta vilões absurdos com muita coragem — e pouca roupa. Com ilustrações divertidas, narrativas cheias de reviravoltas e um toque de irreverência, a série conquista leitores ao unir ação, risadas e imaginação sem limites.",
    autor: autores[9],
    ano: 2017,
    imagem:
      "https://poltronanerd.com.br/wp-content/uploads/2017/10/captainunderpants-1280-1496339994174_1280w.jpg",
    livros: [
      {
        id: "as-aventuras-do-capitao-cueca-1",
        titulo: "As Aventuras do Capitão Cueca",
        autor: autores[9],
        ano: 2017,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81efZ9kHKGL._SY385_.jpg",
        link: "https://amzn.to/4im6juk",
      },
      {
        id: "as-aventuras-do-capitao-cueca-2",
        titulo: "Capitão Cueca e o Ataque das Privadas Falantes",
        autor: autores[9],
        ano: 2017,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/916akMbwa6L._SY385_.jpg",
        link: "https://amzn.to/4gkSrOS",
      },
      {
        id: "as-aventuras-do-capitao-cueca-3",
        titulo: "Capitão Cueca e a invasão das incrivelmente malvadas tias da cantina de outro planeta e o ataque subsequente dos igualmente perversos zumbis nerds",
        autor: autores[9],
        ano: 2017,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81kz6y5JopL._SY385_.jpg",
        link: "https://amzn.to/4fXGwqC",
      },
      {
        id: "as-aventuras-do-capitao-cueca-4",
        titulo: "Capitão Cueca e o perigoso plano secreto do professor Fraldinha Suja",
        autor: autores[9],
        ano: 2018,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/81bvSzdpH-L._SY385_.jpg",
        link: "https://amzn.to/4im0exW",
      },
      {
        id: "as-aventuras-do-capitao-cueca-5",
        titulo: "Capitão Cueca e a fúria da ferocíssima Mulher Tentacular",
        autor: autores[9],
        ano: 2018,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/8184YPG3PJL._SY385_.jpg",
        link: "https://amzn.to/4faJ6Zi",
      },
      {
        id: "as-aventuras-do-capitao-cueca-6",
        titulo: "Capitão Cueca e a grande e desagradável batalha do menino biônico Meleca Seca: Parte 1: A noite das repugnantes Melecas de nariz",
        autor: autores[9],
        ano: 2019,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/71A-eI5HvIL._SY385_.jpg",
        link: "https://amzn.to/4fZaMRN",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-7",
        titulo: "Capitão Cueca e a grande e desagradável batalha do menino biônico Meleca Seca: Parte 2: A revanche dos robôs melequentos ridículos",
        autor: autores[9],
        ano: 2019,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/91eQHQt-z5L._SY385_.jpg",
        link: "https://amzn.to/3ZClSXa",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-8",
        titulo: "Capitão Cueca e a sina ridícula do povo do Penico Roxo",
        autor: autores[9],
        ano: 2020,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/91EHqALW2eL._SY385_.jpg",
        link: "https://amzn.to/49jRfJx",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-9",
        titulo: "Capitão Cueca e o aterrorizante retorno do Caído Tilintar das Calças",
        autor: autores[9],
        ano: 2020,
        ordem: 9,
        imagem: "https://m.media-amazon.com/images/I/91jfcR-T7EL._SY385_.jpg",
        link: "https://amzn.to/3ZDeFWW",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-10",
        titulo: "Capitão Cueca e a revoltante revanche da Robocueca Radioativa",
        autor: autores[9],
        ano: 2021,
        ordem: 10,
        imagem: "https://m.media-amazon.com/images/I/9136Pc1nZ6L._SY385_.jpg",
        link: "https://amzn.to/4g0SiR2",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-11",
        titulo: "Capitão Cueca e a tirânica retaliação da Privada Turbo 2000",
        autor: autores[9],
        ano: 2021,
        ordem: 11,
        imagem: "https://m.media-amazon.com/images/I/81TpFUTUlNS._SY385_.jpg",
        link: "https://amzn.to/3Zottaw",
      },     
      {
        id: "as-aventuras-do-capitao-cueca-12",
        titulo: "Capitão Cueca e a saga sensacional de Fedor, O Grande",
        autor: autores[9],
        ano: 2022,
        ordem: 12,
        imagem: "https://m.media-amazon.com/images/I/91-E46av99L._SY385_.jpg",
        link: "https://amzn.to/41hZi7s",
      },     
      
    ],
  },
  {
    id: "o-homem-cao",
    titulo: "O Homem-Cão",
    descricao:
      "O Homem-Cão, de Dav Pilkey, é uma série de livros infantojuvenis que mistura humor, ação e criatividade em uma narrativa única. A história acompanha um policial que, após um acidente, tem seu corpo fundido com a cabeça de um cachorro, transformando-se no heróico e hilário Homem-Cão. Agora, com sua lealdade canina e inteligência humana, ele enfrenta vilões excêntricos, como o astuto gato Petey, enquanto aprende a lidar com suas novas habilidades e desafios. Com ilustrações vibrantes, piadas cativantes e mensagens sobre amizade, perseverança e empatia, Homem-Cão encanta leitores de todas as idades.",
    autor: autores[9],
    ano: 2017,
    imagem:
      "https://p2.trrsf.com/image/fget/cf/1200/900/middle/images.terra.com/2024/09/17/unnamed-r1csu98vvn09.jpg",
    livros: [
      {
        id: "o-homem-cao-1",
        titulo: "O Homem-Cão",
        autor: autores[9],
        ano: 2017,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81DW1gZuEfL._SY425_.jpg",
        link: "https://amzn.to/49oz6KH",
      },
      {
        id: "o-homem-cao-2",
        titulo: "O Homem-Cão desgovernado",
        autor: autores[9],
        ano: 2018,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91XDd5k0qXL._SY425_.jpg",
        link: "https://amzn.to/3Zow6ZW",
      },
      {
        id: "o-homem-cao-3",
        titulo: "O Homem-Cão: Um conto de dois gatinhos",
        autor: autores[9],
        ano: 2018,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81s79ir0X8L._SY425_.jpg",
        link: "https://amzn.to/3B0NFY8",
      },
      {
        id: "o-homem-cao-4",
        titulo: "O Homem-Cão e o Supergatinho",
        autor: autores[9],
        ano: 2019,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/81ZOaAaFeFL._SY425_.jpg",
        link: "https://amzn.to/4f0W4Zu",
      },
      {
        id: "o-homem-cao-5",
        titulo: "O Homem-Cão: O senhor das pulgas",
        autor: autores[9],
        ano: 2019,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/811ta+Utd1L._SY425_.jpg",
        link: "https://amzn.to/3ODleCL",
      },
      {
        id: "o-homem-cao-6",
        titulo: "O Homem-Cão: O confronto selvagem",
        autor: autores[9],
        ano: 2020,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/91NZGONlD9L._SY425_.jpg",
        link: "https://amzn.to/3VqloAZ",
      },     
      {
        id: "o-homem-cao-7",
        titulo: "O Homem-Cão: Por quem as bolas rolam",
        autor: autores[9],
        ano: 2020,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/91VWvX7blSL._SY425_.jpg",
        link: "https://amzn.to/4fVjxN1",
      },     
      {
        id: "o-homem-cao-8",
        titulo: "O Homem-Cão: Latiu-22",
        autor: autores[9],
        ano: 2021,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/91Fmp+GBpxS._SY425_.jpg",
        link: "https://amzn.to/3BaadFR",
      },     
      {
        id: "o-homem-cao-9",
        titulo: "O Homem-Cão: Imundície e castigo",
        autor: autores[9],
        ano: 2022,
        ordem: 9,
        imagem: "https://m.media-amazon.com/images/I/81LS61OUGuL._SY425_.jpg",
        link: "https://amzn.to/3VmMOaW",
      },     
      {
        id: "o-homem-cao-10",
        titulo: "O Homem-Cão: Mamãe dos ventos uivantes",
        autor: autores[9],
        ano: 2022,
        ordem: 10,
        imagem: "https://m.media-amazon.com/images/I/71lE3-fKVaL._SY425_.jpg",
        link: "https://amzn.to/49lHI4w",
      },     
      {
        id: "o-homem-cao-11",
        titulo: "O Homem-Cão: Vinte mil pulgas submarinas",
        autor: autores[9],
        ano: 2024,
        ordem: 11,
        imagem: "https://m.media-amazon.com/images/I/81He-gi3X0L._SY425_.jpg",
        link: "https://amzn.to/4eWCEEY",
      },     
      
    ],
  },
  {
    id: "mortina",
    titulo: "Mortina",
    descricao:
      "Mortina, de Barbara Cantini, é uma encantadora série de livros infantojuvenis que combina humor, mistério e uma dose de macabra diversão. A protagonista, Mortina, é uma menina zumbi que vive em uma mansão assombrada com sua excêntrica tia e seu fiel cachorro albino, Tristonho. Apesar de ser diferente das outras crianças, Mortina sonha em fazer amigos e viver aventuras fora do mundo dos mortos. Com ilustrações delicadas e uma narrativa leve, a série aborda temas como aceitação, amizade e autenticidade, encantando leitores com seu charme único e atmosfera mágica.",
    autor: autores[10],
    ano: 2019,
    imagem:
      "https://deliriumnerd.com/wp-content/uploads/2019/05/89247EB1-3324-468C-AE82-F923AE77D485.jpeg",
    livros: [
      {
        id: "mortina-1",
        titulo: "Mortina",
        autor: autores[10],
        ano: 2019,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/A1hFhgISH9L._SY425_.jpg",
        link: "https://amzn.to/41mWZjB",
      },
      {
        id: "mortina-2",
        titulo: "Mortina e o primo insuportável",
        autor: autores[10],
        ano: 2019,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91e9ZKoPXnL._SY425_.jpg",
        link: "https://amzn.to/3OGNbJW",
      },
      {
        id: "mortina-3",
        titulo: "Mortina e o amigo fantasma",
        autor: autores[10],
        ano: 2020,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/91ui8u+xz7L._SY425_.jpg",
        link: "https://amzn.to/3CXZleG",
      },
      {
        id: "mortina-4",
        titulo: "Mortina de férias no Lago do Mistério",
        autor: autores[10],
        ano: 2021,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/91hFne2EX2L._SY425_.jpg",
        link: "https://amzn.to/3ZBa1c1",
      },
      {
        id: "mortina-5",
        titulo: "Mortina e uma surpresa de arrepiar",
        autor: autores[10],
        ano: 2023,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/A122svPcsXL._SY425_.jpg",
        link: "https://amzn.to/4eZSPRT",
      },
           
      
    ],
  },
];

export default series;
