import autores from "./autores";

const series = [
  {
    id: "harry-potter",
    titulo: "Harry Potter",
    descricao:
      "A série de livros Harry Potter, escrita por J.K. Rowling, segue a jornada de um jovem bruxo, Harry Potter, enquanto ele descobre seu lugar no mundo mágico e enfrenta desafios para derrotar o malvado bruxo Lord Voldemort. Ao longo de sete livros, Harry e seus amigos, Hermione Granger e Ron Weasley, exploram a magia, enfrentam perigos e aprendem sobre amizade, coragem e o poder da escolha em uma luta épica entre o bem e o mal.",
    autor: autores[0],
    ano: 1997,
    imagem:
      "https://ingresso-a.akamaihd.net/b2b/production/uploads/article/image/2549/7ababc2015043445b750ebc853a5f706.jpg",
    livros: [
      {
        id: "harry-potter-e-a-pedra-filosofal",
        titulo: "Harry Potter e a Pedra Filosofal",
        autor: autores[0],
        ano: 1997,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81pB+joKL4L._SL1500_.jpg",
        link: "https://amzn.to/49heZ0X",
      },
      {
        id: "harry-potter-e-a-camara-secreta",
        titulo: "Harry Potter e a Câmara Secreta",
        autor: autores[0],
        ano: 1998,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/81D+5aMHzFL._SL1500_.jpg",
        link: "https://amzn.to/3B702Sg",
      },
      {
        id: "harry-potter-e-o-prisioneiro-de-azkaban",
        titulo: "Harry Potter e o Prisioneiro de Azkaban",
        autor: autores[0],
        ano: 1999,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81Q+2zleuwL._SL1500_.jpg",
        link: "https://amzn.to/3B46wS0",
      },
      {
        id: "harry-potter-e-o-calice-de-fogo",
        titulo: "Harry Potter e o Cálice de Fogo",
        autor: autores[0],
        ano: 2000,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/81IsnaNraBL._SL1500_.jpg",
        link: "https://amzn.to/41d45ay",
      },
      {
        id: "harry-potter-e-a-ordem-da-fenix",
        titulo: "Harry Potter e a Ordem da Fênix",
        autor: autores[0],
        ano: 2003,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/81ZQUV67MGL._SL1500_.jpg",
        link: "https://amzn.to/3Zw4ZgU",
      },
      {
        id: "harry-potter-e-o-enigma-do-principe",
        titulo: "Harry Potter e o Enigma do Príncipe",
        autor: autores[0],
        ano: 2005,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/81SZC96OGOL._SL1500_.jpg",
        link: "https://amzn.to/4ibXDXg",
      },
      {
        id: "Harry Potter e as Reliquias da Morte",
        titulo: "Harry Potter e as Relíquias da Morte",
        autor: autores[0],
        ano: 2007,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/81PbdwXqKkL._SL1500_.jpg",
        link: "https://amzn.to/3CUdBFl",
      },
      {
        id: "harry-potter-e-a-crianca-amaldicoada",
        titulo: "Harry Potter e a Criança Amaldiçoada",
        autor: autores[0],
        ano: 2016,
        ordem: 8,
        imagem: "https://rocco.com.br/app/uploads/2024/04/9786555322682.jpg",
        link: "https://amzn.to/3ZevtlR",
      },
    ],
  },
  {
    id: "o-senhor-dos-aneis",
    titulo: "O Senhor dos Anéis",
    descricao:
      "A trilogia O Senhor dos Anéis, escrita por J.R.R. Tolkien, narra a aventura épica de Frodo Bolseiro, um hobbit que recebe a missão de destruir o poderoso Anel do Poder e impedir que ele caia nas mãos do sombrio Senhor Sauron. Acompanhado por um grupo diverso de heróis, Frodo enfrenta batalhas, perigos sobrenaturais e tentações, em uma jornada que explora temas de coragem, sacrifício e amizade. A história celebra a luta do bem contra o mal em um vasto e detalhado mundo de fantasia, a Terra-média.",
    autor: autores[1],
    ano: 1954,
    imagem:
      "https://cinepop.com.br/wp-content/uploads/2021/12/o-senhor-dos-aneis.jpg",
    livros: [
      {
        id: "a-sociedade-do-anel",
        titulo: "A Sociedade do Anel",
        autor: autores[1],
        ano: 1954,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg",
        link: "https://amzn.to/49htqlr",
      },
      {
        id: "as-duas-torres",
        titulo: "As Duas Torres",
        autor: autores[1],
        ano: 1954,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/81N9hxO6XdL._SL1500_.jpg",
        link: "https://amzn.to/3CMSgxm",
      },
      {
        id: "o-retorno-do-rei",
        titulo: "O Retorno do Rei",
        autor: autores[1],
        ano: 1955,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81LUEEYfQNL._SL1500_.jpg",
        link: "https://amzn.to/3D1Tmp0",
      },
    ],
  },
  {
    id: "as-cronicas-de-gelo-e-fogo",
    titulo: "As Crônicas de Gelo e Fogo",
    descricao:
      "As Crônicas de Gelo e Fogo, série escrita por George R.R. Martin, acompanha a luta pelo Trono de Ferro em Westeros, um continente marcado por rivalidades, alianças e traições. Nobres famílias, como os Starks, Lannisters e Targaryens, jogam um perigoso jogo de intrigas, onde poder e sobrevivência andam lado a lado. Enquanto reis e rainhas disputam o controle dos Sete Reinos, uma antiga ameaça cresce ao norte, e o inverno se aproxima, trazendo consigo o perigo dos Caminhantes Brancos. A série explora temas de poder, lealdade e moralidade em uma narrativa complexa e repleta de reviravoltas.",
    autor: autores[2],
    ano: 1996,
    imagem:
      "https://img.odcdn.com.br/wp-content/uploads/2024/07/Design-sem-nome-16-1-scaled.jpg",
    livros: [
      {
        id: "a-guerra-dos-tronos",
        titulo: "A Guerra dos Tronos",
        autor: autores[2],
        ano: 1996,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/91eHityofNL._SL1500_.jpg",
        link: "https://amzn.to/3CWfCAY",
      },
      {
        id: "a-furia-dos-reis",
        titulo: "A Fúria dos Reis",
        autor: autores[2],
        ano: 1998,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/91N6C0jwzuL._SL1500_.jpg",
        link: "https://amzn.to/3ZckitU",
      },
      {
        id: "a-tormenta-de-espadas",
        titulo: "A Tormenta de Espadas",
        autor: autores[2],
        ano: 2000,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/91VVZ-v5GYL._SL1500_.jpg",
        link: "https://amzn.to/3CSvhBc",
      },
      {
        id: "o-festim-dos-corvos",
        titulo: "O Festim dos Corvos",
        autor: autores[2],
        ano: 2019,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/814UZhEYFfL._SL1500_.jpg",
        link: "https://amzn.to/3ZtIRUu",
      },
      {
        id: "a-danca-dos-dragoes",
        titulo: "A Dança dos Dragões",
        autor: autores[2],
        ano: 2020,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/91DisjRjFxL._SL1500_.jpg",
        link: "https://amzn.to/3Ozr8os",
      },
    ],
  },
  {
    id: "diario-de-um-banana",
    titulo: "Diário de um Banana",
    descricao:
      "Diário de um Banana é uma série de livros infantojuvenis escrita por Jeff Kinney, que combina humor, ilustrações em estilo de tirinhas e histórias cativantes sobre a vida de Greg Heffley, um adolescente comum que enfrenta os altos e baixos da escola e da convivência com sua peculiar família. Com um tom leve e bem-humorado, a série aborda temas como amizade, desafios escolares, embaraços do crescimento e as aventuras do cotidiano de forma acessível e divertida. Os livros têm um estilo de narrativa em forma de diário ilustrado, que conquistou milhões de leitores ao redor do mundo, tornando-se um fenômeno da literatura juvenil.",
    autor: autores[3],
    ano: 2007,
    imagem:
      "https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2021/11/13/1443507557-diary-of-a-wimpy-kid.jpg",
    livros: [
      {
        id: "diario-de-um-banana-1",
        titulo: "Diário de um Banana 1",
        autor: autores[3],
        ano: 2008,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/71fWaI5myqL._SY385_.jpg",
        link: "https://amzn.to/4f0OOwy",
      },
      {
        id: "diario-de-um-banana-2",
        titulo: "Diário de um Banana 2: Rodrick é o cara",
        autor: autores[3],
        ano: 2009,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/71+fh2vstSL._SY385_.jpg",
        link: "https://amzn.to/4197nv9",
      },
      {
        id: "diario-de-um-banana-3",
        titulo: "Diário de um Banana 3: A gota d’água",
        autor: autores[3],
        ano: 2010,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/81T9BY8yEnL._SY385_.jpg",
        link: "https://amzn.to/41aONCS",
      },
      {
        id: "diario-de-um-banana-4",
        titulo: "Diário de um Banana 4: Dias de Cão",
        autor: autores[2],
        ano: 2011,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/71MuD6Hn8OL._SY385_.jpg",
        link: "https://amzn.to/4g8O1us",
      },
      {
        id: "diario-de-um-banana-5",
        titulo: "Diário de um Banana 5: A verdade nua e crua",
        autor: autores[3],
        ano: 2011,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/711dw9VO+jL._SY385_.jpg",
        link: "https://amzn.to/4g8zcYT",
      },
      {
        id: "diario-de-um-banana-6",
        titulo: "Diário de um Banana 6: Casa dos horrores",
        autor: autores[3],
        ano: 2012,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/71beaUwsF0L._SY385_.jpg",
        link: "https://amzn.to/4g9VrO8",
      },
      {
        id: "diario-de-um-banana-7",
        titulo: "Diário de um Banana 7: Segurando vela",
        autor: autores[3],
        ano: 2013,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/71gWCy-KesL._SY385_.jpg",
        link: "https://amzn.to/3VhvmEC",
      },
      {
        id: "diario-de-um-banana-8",
        titulo: "Diário de um Banana 8: Maré de azar",
        autor: autores[3],
        ano: 2014,
        ordem: 8,
        imagem: "https://m.media-amazon.com/images/I/716yGyLTIxL._SY385_.jpg",
        link: "https://amzn.to/3VhvpQO",
      },
      {
        id: "diario-de-um-banana-9",
        titulo: "Diário de um Banana 9: Caindo na estrada",
        autor: autores[3],
        ano: 2015,
        ordem: 9,
        imagem: "https://m.media-amazon.com/images/I/71D7-E0gtIL._SY385_.jpg",
        link: "https://amzn.to/4f3qOJq",
      },
      {
        id: "diario-de-um-banana-10",
        titulo: "Diário de um Banana 10: Bons tempos",
        autor: autores[3],
        ano: 2015,
        ordem: 10,
        imagem: "https://m.media-amazon.com/images/I/71ci78zaT-L._SY385_.jpg",
        link: "https://amzn.to/4fRin4O",
      },
      {
        id: "diario-de-um-banana-11",
        titulo: "Diário de um Banana 11: Vai ou racha",
        autor: autores[3],
        ano: 2016,
        ordem: 11,
        imagem: "https://m.media-amazon.com/images/I/718cIIlLIwL._SY385_.jpg",
        link: "https://amzn.to/3B8g12E",
      },
      {
        id: "diario-de-um-banana-12",
        titulo: "Diário de um Banana 12: Apertem os cintos",
        autor: autores[3],
        ano: 2017,
        ordem: 12,
        imagem: "https://m.media-amazon.com/images/I/71vHGC4hRmL._SY385_.jpg",
        link: "https://amzn.to/3B2fwXP",
      },
      {
        id: "diario-de-um-banana-13",
        titulo: "Diário de um Banana 13: Batalha Neval",
        autor: autores[3],
        ano: 2018,
        ordem: 13,
        imagem: "https://m.media-amazon.com/images/I/71AII-WDnXL._SY385_.jpg",
        link: "https://amzn.to/4idwbIA",
      },
      {
        id: "diario-de-um-banana-14",
        titulo: "Diário de um Banana 14: Quebra Tudo",
        autor: autores[3],
        ano: 2019,
        ordem: 14,
        imagem: "https://m.media-amazon.com/images/I/71RqnIKaA9L._SY385_.jpg",
        link: "https://amzn.to/3CTuOi3",
      },
      {
        id: "diario-de-um-banana-15",
        titulo: "Diário de um Banana 15: Vai Fundo",
        autor: autores[3],
        ano: 2020,
        ordem: 15,
        imagem: "https://m.media-amazon.com/images/I/71qp05Xbw9L._SY385_.jpg",
        link: "https://amzn.to/4fSEYy1",
      },
      {
        id: "diario-de-um-banana-16",
        titulo: "Diário de um Banana 16: Bola Fora",
        autor: autores[3],
        ano: 2021,
        ordem: 16,
        imagem: "https://m.media-amazon.com/images/I/91Bd39WTNuL._SY385_.jpg",
        link: "https://amzn.to/3VfwIQm",
      },
      {
        id: "diario-de-um-banana-17",
        titulo: "Diário de um Banana 17: Fräwda Megaxeia",
        autor: autores[3],
        ano: 2022,
        ordem: 17,
        imagem: "https://m.media-amazon.com/images/I/916K1XCNRBL._UF894,1000_QL80_.jpg",
        link: "https://amzn.to/3VkQdqL",
      },
      {
        id: "diario-de-um-banana-18",
        titulo: "Diário de um Banana 18: Cabeça-oca",
        autor: autores[3],
        ano: 2023,
        ordem: 18,
        imagem: "https://m.media-amazon.com/images/I/71HODD5GbdL._AC_UF1000,1000_QL80_.jpg",
        link: "https://amzn.to/4eVdIOd",
      },
      {
        id: "diario-de-um-banana-19",
        titulo: "Diário de um Banana 19: Baita lambança",
        autor: autores[3],
        ano: 2024,
        ordem: 19,
        imagem: "https://m.media-amazon.com/images/I/71GJo0STB8L._SY385_.jpg",
        link: "https://amzn.to/3D2gC6h",
      },
    ],
  },
  {
    id: "maze-runner",
    titulo: "Maze Runner",
    descricao:
      "Maze Runner, de James Dashner, é uma série de ficção científica que acompanha Thomas, um jovem que acorda sem memória em uma Clareira cercada por um misterioso labirinto cheio de perigos. Junto com outros adolescentes, ele precisa desvendar os segredos por trás do labirinto e enfrentar desafios mortais em um mundo pós-apocalíptico. Com uma narrativa repleta de ação, suspense e reviravoltas, a série explora temas de sobrevivência, amizade e sacrifício, conquistando leitores ao redor do mundo.",
    autor: autores[4],
    ano: 1992,
    imagem:
      "https://i0.wp.com/tapipocando.com.br/wp-content/uploads/2024/05/Maze-Runner.jpg?fit=1920%2C1080&ssl=1",
    livros: [
      {
        id: "maze-runner-1",
        titulo: "Maze Runner: ordem de extermínio",
        autor: autores[4],
        ano: 2013,
        ordem: 1,
        imagem: "https://m.media-amazon.com/images/I/61ILpNSiAuL._SY385_.jpg",
        link: "https://amzn.to/49huiqd",
      },
      {
        id: "maze-runner-2",
        titulo: "Maze Runner: Arquivos",
        autor: autores[4],
        ano: 2014,
        ordem: 2,
        imagem: "https://m.media-amazon.com/images/I/51MTj2LpsQL._SY385_.jpg",
        link: "https://amzn.to/4eTDylE",
      },
      {
        id: "maze-runner-3",
        titulo: "Maze Runner: Correr ou Morrer",
        autor: autores[4],
        ano: 2010,
        ordem: 3,
        imagem: "https://m.media-amazon.com/images/I/51UqHWh58-L._SY445_SX342_.jpg",
        link: "https://amzn.to/49dil4M",
      },
      {
        id: "maze-runner-4",
        titulo: "Maze Runner: Prova de Fogo",
        autor: autores[4],
        ano: 2011,
        ordem: 4,
        imagem: "https://m.media-amazon.com/images/I/61pGP-2ZaCL._SY385_.jpg",
        link: "https://amzn.to/3COnapk",
      },
      {
        id: "maze-runner-5",
        titulo: "Maze Runner: A Cura Mortal",
        autor: autores[4],
        ano: 2012,
        ordem: 5,
        imagem: "https://m.media-amazon.com/images/I/61pR3wqzNgL._SY385_.jpg",
        link: "https://amzn.to/49fq822",
      },
      {
        id: "maze-runner-6",
        titulo: "Crank Palace: A Maze Runner Novella",
        autor: autores[4],
        ano: 2012,
        ordem: 6,
        imagem: "https://m.media-amazon.com/images/I/81AtmD2CM2L._SY385_.jpg",
        link: "https://amzn.to/4g9QBAq",
      },
      {
        id: "maze-runner-7",
        titulo: "Box Maze Runner - Edição completa",
        autor: autores[4],
        ano: 2018,
        ordem: 7,
        imagem: "https://m.media-amazon.com/images/I/81UckzVmQPL._SY385_.jpg",
        link: "https://amzn.to/3B80pMm",
      },
      
    ],
  },
];

export default series;
